version: "3.7"

services: 
    nginx-proxy:
        image: nginx:alpine
        ports:
        - "80:80"
        volumes:
          - ./:/var/www/html
    
    e-prov:
        image: php:7.3.26-fpm-alpine
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html/
        working_dir: /var/www/html
    db:
        image: postgres:12.2-alpine
        ports:
        - 5432:5432
        volumes:
        - ./:/home
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        restart: always

    db_test:
        image: postgres:12.2-alpine
        ports:
        - 5435:5432
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    mailhog:
        image: mailhog/mailhog:latest
        ports:
        - 8025:8025
