FROM nginx:1.19.0-alpine

COPY ./docker/website.conf /etc/nginx/conf.d/default.conf

COPY ./docker/nginx.conf /etc/nginx/nginx.conf

RUN apk add tzdata && cp /usr/share/zoneinfo/America/Buenos_Aires /etc/localtime
